# Generated by Django 2.1.7 on 2019-09-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=75)),
                ('phone', models.EmailField(max_length=75)),
                ('whats', models.EmailField(max_length=75)),
                ('services', models.EmailField(max_length=75)),
                ('text', models.TextField()),
            ],
        ),
    ]
