# Generated by Django 2.1.7 on 2019-09-29 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='file',
            field=models.ImageField(default='defualt.png', upload_to=''),
        ),
    ]
