# Generated by Django 2.1.7 on 2019-10-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20190929_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_service',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_service',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_service',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_service',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
