# Generated by Django 2.1.7 on 2019-10-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20191001_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
