# Generated by Django 2.1.7 on 2019-10-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20191001_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_service',
            old_name='received',
            new_name='solving',
        ),
    ]
