# Generated by Django 2.1.7 on 2019-10-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20191001_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
