# Generated by Django 2.2.6 on 2019-10-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20191001_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service',
            name='email',
            field=models.EmailField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='user_service',
            name='whatsapp_number',
            field=models.IntegerField(null=True),
        ),
    ]
